spring.application.name=Resale-Auction Marketplace

#MySQL DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# poll size
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2


spring.datasource.hikari.max-lifetime=1700000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=300000

# ??? ??/?? ?? ??
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000


#JPA ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace


# Redis
spring.data.redis.sentinel.master=${SPRING_REDIS_SENTINEL_MASTER}
spring.data.redis.sentinel.nodes=${SPRING_REDIS_SENTINEL_NODES}